#!/usr/bin/env zsh

# ~/.aliases
# =============================================================================

# Shortcuts
alias shrug="echo '¯\_(ツ)_/¯' | pbcopy"
alias c="clear"
alias ls="eza --long --header --icons --all"
alias profile="code ~/.zprofile"
alias aliases="code ~/.aliases"
alias -s txt="code -t"
alias ~="cd ~"
alias rm="rm -i"

# Directories
alias dotfiles="cd $DOTFILES"
alias library="cd $HOME/Library"
alias cupcake="cd $PROJECTS/@me/@cupcake"

# macOS

# Recursively delete .DS_Store files
alias cleanupDS="find . -type f -name '*.DS_Store' -ls -delete"

# Show/Hide hidden files in Finder
alias showFiles="defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder"
alias hideFiles="defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder"

# Hide/show all desktop icons (useful when presenting)
alias hidedesktop="defaults write com.apple.finder CreateDesktop -bool false && killall Finder"
alias showdesktop="defaults write com.apple.finder CreateDesktop -bool true && killall Finder"

# Edit /etc/hosts file
alias editHosts="code /etc/hosts"
