#!/usr/bin/env zsh

clear

# History setup
HISTFILE=$HOME/.zsh_history
HISTSIZE=100000
SAVEHIST=$HISTSIZ

setopt hist_ignore_all_dups # remove older duplicate entries from history
setopt hist_reduce_blanks # remove superfluous blanks from history items
setopt inc_append_history # save history entries as soon as they are entered
setopt share_history # share history between different instances of the shell
setopt auto_cd # cd by typing directory name if it's not a command
setopt correct # autocorrect
setopt correct_all # autocorrect commands
setopt auto_list # automatically list choices on ambiguous completion
setopt auto_menu # automatically use menu completion
setopt always_to_end # move cursor to end if word had one match

# Completion system
autoload -Uz compinit && compinit
autoload bashcompinit && bashcompinit # load bashcompinit for some old bash completions

###############################################################################
# INSTALL DEPS
###############################################################################
if [[ ! -f ~/.zsh/antigen.zsh ]]; then
  curl -L git.io/antigen > ~/.zsh/antigen.zsh
fi

if [[ ! -f ~/.extra ]]; then
  touch ~/.extra
fi

###############################################################################
# PLUGINS && SUCH
###############################################################################
source $HOME/.zsh/antigen.zsh
antigen bundle zpm-zsh/ls

###############################################################################
# EXPORTS
###############################################################################
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

export EDITOR=nano
export VISUAL=$EDITOR
export DROPBOX=$HOME/Dropbox
export DOTFILES=$HOME/.dotfiles
export DOTFILES=$HOME/.local/share/chezmoi
export PROJECTS=$HOME/@Projects
export BEYHIVE=$PROJECTS/@beyhive
export WIP=$PROJECTS/@wip

###############################################################################
# Load the shell dotfiles, and then some:
###############################################################################
if [[ ! -f ~/.zsh/yonce/yonce.zsh ]]
  antigen theme geometry-zsh/geometry
then
else
  source $HOME/.zsh/yonce/yonce.zsh
fi

source $HOME/.path
source $HOME/.aliases
source $HOME/.functions
source $HOME/.extra

antigen apply

###############################################################################
# PDE SETUP || 2022-02-11T02:04:21-0800
###############################################################################
/usr/bin/ssh-add -A >/dev/null 2>&1
