#!/usr/bin/env zsh

# ~/.zprofile
# =============================================================================
# Executed by Z shell for interactive shells.
# See http://zsh.sourceforge.net/

# Homebrew shell setup
eval "$(/opt/homebrew/bin/brew shellenv)"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
# [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
