#!/usr/bin/env zsh

###############################################################################
# Variables
###############################################################################
WORKSPACE=$DROPBOX/.the.setup

SLAY_SCREENSHOTS="$HOME/@Inbox/@Screenshots"
SLAY_HOSTNAME="Peppermint"

DIRECTORIES=(
    $HOME/@Inbox
    $HOME/@Inbox/@Apps
    $HOME/@Inbox/@Audio
    $HOME/@Inbox/@Design
    $HOME/@Inbox/@Documents
    $HOME/@Inbox/@Folders
    $HOME/@Inbox/@Images
    $HOME/@Inbox/@Misc
    $HOME/@Inbox/@Movies
    $HOME/@Inbox/@Outbox
    $HOME/@Inbox/@Screenshots
    $HOME/@Inbox/@Zips
    $HOME/@Projects
    $HOME/@Projects/@beyhive
    $HOME/@Projects/@wip
)

EMOJIONE_URL="https://github.com/emojione/emojione-assets/releases/download/3.1.2/emojione-apple.ttf"

NERDFONTS_RELEASE=$(curl -L -s -H 'Accept: application/json' https://github.com/ryanoasis/nerd-fonts/releases/latest)
NERDFONTS_VERSION=$(get_github_version $NERDFONTS_RELEASE)

NERDFONTS=(
    Hack
    AnonymousPro
    Inconsolata
)

###############################################################################
# Customizations
###############################################################################

step "Making directories…"
for dir in ${DIRECTORIES[@]}; do
    mkd $dir
done

if [[ $(cli_is_installed fileicon) == 1 ]]; then
	echo "${indent}  ︎︎❤︎ Customizing folder icons…"
	fileicon set $HOME/@Inbox $WORKSPACE/icons/folders--gradient/downloads/icon-folders/download-folder.png
	fileicon set $HOME/@Inbox/@Apps $WORKSPACE/icons/folders--gradient/downloads/icon-folders/heart-folder.png
	fileicon set $HOME/@Inbox/@Audio $WORKSPACE/icons/folders--gradient/downloads/icon-folders/music-folder.png
	fileicon set $HOME/@Inbox/@Documents $WORKSPACE/icons/folders--gradient/downloads/icon-folders/documents-folder.png
	fileicon set $HOME/@Inbox/@Folders $WORKSPACE/icons/folders--gradient/downloads/icon-folders/star-folder.png
	fileicon set $HOME/@Inbox/@Images $WORKSPACE/icons/folders--gradient/downloads/icon-folders/photos-folder.png
	fileicon set $HOME/@Inbox/@Misc $WORKSPACE/icons/folders--gradient/downloads/icon-folders/bin-folder.png
	fileicon set $HOME/@Inbox/@Movies $WORKSPACE/icons/folders--gradient/downloads/icon-folders/video-folder.png
	fileicon set $HOME/@Inbox/@Screenshots $WORKSPACE/icons/folders--gradient/downloads/icon-folders/screenshots-folder.png
	fileicon set $HOME/@Inbox/@Zips $WORKSPACE/icons/folders--gradient/downloads/icon-folders/smile-folder.png
	fileicon set $PROJECTS $WORKSPACE/icons/folders--gradient/downloads/icon-folders/crown-folder.png

	if [ -d "$HOME/Dropbox" ]; then
		fileicon set $DROPBOX/@financial $WORKSPACE/icons/folders--gradient/downloads/icon-folders/money-folder.png
		fileicon set $DROPBOX/@legacy $WORKSPACE/icons/folders--gradient/downloads/icon-folders/heart-folder.png
		fileicon set $DROPBOX/@legal $WORKSPACE/icons/folders--gradient/downloads/icon-folders/doodle-folder.png
		fileicon set $DROPBOX/@medical $WORKSPACE/icons/folders--gradient/downloads/icon-folders/sparkles-folder.png
		fileicon set $DROPBOX/apps $WORKSPACE/icons/folders--gradient/downloads/icon-folders/download-folder.png
		fileicon set $DROPBOX/brag.file $WORKSPACE/icons/folders--gradient/downloads/icon-folders/crown-folder.png
		fileicon set $DROPBOX/documents $WORKSPACE/icons/folders--gradient/downloads/icon-folders/documents-folder.png
		fileicon set $DROPBOX/front.porch $WORKSPACE/icons/folders--gradient/downloads/icon-folders/smile-folder.png
		fileicon set $DROPBOX/learning $WORKSPACE/icons/folders--gradient/downloads/icon-folders/z-js-folder.png
		fileicon set $DROPBOX/personal $WORKSPACE/icons/folders--gradient/downloads/icon-folders/calligraphy-folder.png
		fileicon set $DROPBOX/Photos $WORKSPACE/icons/folders--gradient/downloads/icon-folders/photos-folder.png
		fileicon set $DROPBOX/projects $WORKSPACE/icons/folders--gradient/downloads/icon-folders/code-folder.png
		fileicon set $DROPBOX/resources $WORKSPACE/icons/folders--gradient/downloads/icon-folders/type-folder.png
		fileicon set $DROPBOX/shared $WORKSPACE/icons/folders--gradient/downloads/icon-folders/star-folder.png
		fileicon set $DROPBOX/speaking $WORKSPACE/icons/folders--gradient/downloads/icon-folders/talks-folder.png
		fileicon set $DROPBOX/the.setup $WORKSPACE/icons/folders--gradient/downloads/icon-folders/home-folder.png
	fi

	print_in_green "${bold}✓ done!${normal}\n"
else
	print_error "fileicon must be installed! Skipping."
fi


step "Cloning repositories..."

git clone git@github.com:minamarkham/dotfiles.git $HOME/.dotfiles

git clone git@github.com:minamarkham/cupcake.git $PROJECTS/@cupcake
git clone git@github.com:minamarkham/mdash.wtf.git $PROJECTS/@mdash
git clone git@github.com:minamarkham/setup.git $PROJECTS/setup
git clone git@github.com:minamarkham/speedlify.git $PROJECTS/speedlify
git clone git@github.com:minamarkham/twitter-archive.git $PROJECTS/twitter-archive
git clone git@github.com:minamarkham/minamarkham.git $PROJECTS/minamarkham

git clone git@github.com:minamarkham/yonce.git $BEYHIVE/yonce
git clone git@github.com:minamarkham/yonce-vscode.git  $BEYHIVE/yonce-vscode
git clone git@github.com:minamarkham/yonce-prompt.git $BEYHIVE/yonce-prompt
git clone git@github.com:minamarkham/yonce-visual-studio.git  $BEYHIVE/yonce-visual-studio

git clone git@github.com:minamarkham/formation.git $BEYHIVE/formation
git clone git@github.com:minamarkham/httpbey.git $BEYHIVE/httpbey
git clone git@github.com:minamarkham/711ty.git $BEYHIVE/711ty

git clone git@github.com:minamarkham/beyonce-ipsum.git $WIP/beyonce-ipsum
git clone git@github.com:minamarkham/xo.git  $WIP/XO
git clone git@github.com:minamarkham/beygifs.git $WIP/beygifs
git clone git@github.com:minamarkham/partition.git  $WIP/partition

step "Customizing Mac…"
if [ $HOSTNAME != $SLAY_HOSTNAME ]; then
    printf "${indent}    ❤︎ Setting computer name… "
    scutil --set ComputerName $SLAY_HOSTNAME && \
    scutil --set HostName $SLAY_HOSTNAME && \
    scutil --set LocalHostName $SLAY_HOSTNAME
    print_in_green "${bold}✓ done!${normal}\n"
else
    print_muted "${indent}✓ Computer name already set. Skipped."
fi

echo "${indent}  ︎︎❤︎ Showing hidden files…"
defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder

echo "${indent}  ︎︎❤︎ Configuring screenshots…"
defaults write com.apple.screencapture type jpg
defaults write com.apple.screencapture location $SLAY_SCREENSHOTS
killall SystemUIServer

step "Switching emojis to EmojiOne…"
if [ ! -f ~/Library/Fonts/emojione-apple.ttf ]; then
    printf "${indent}  [↓] EmojiOne "
    wget -P ~/Library/Fonts $EMOJIONE_URL --quiet
    print_in_green "${bold}✓ done!${normal}\n"
else
    print_muted "${indent}✓ EmojiOne already installed. Skipped."
fi

step "Installing fonts…"
for font in ${NERDFONTS[@]}; do
    if [ ! -d ~/Library/Fonts/$font ]; then
        printf "${indent}  [↓] $font "
        wget -P ~/Library/Fonts https://github.com/ryanoasis/nerd-fonts/releases/download/$NERDFONTS_VERSION/$font.zip --quiet;unzip -q ~/Library/Fonts/$font -d ~/Library/Fonts/$font
        print_in_green "${bold}✓ done!${normal}\n"
    else
        print_muted "${indent}✓ $font already installed. Skipped."
    fi
done

###############################################################################
# OPTIONAL: Follow-ups
###############################################################################
title "Next steps…"
todo "Complete setup checklist: ${bold}https://github.com/minamarkham/setup/blob/master/checklist.md${reset}"