#!/usr/bin/env zsh

# ~/.exports
# =============================================================================
export EDITOR=micro # nano
export VISUAL=$EDITOR
export DROPBOX=$HOME/Dropbox
export INBOX=$HOME/@Inbox
export DOTFILES=$HOME/.local/share/chezmoi
export PROJECTS=$HOME/@Projects
export WIP=$PROJECTS/!wip
export WORKSPACE=$WIP/workspace
export HOMEBREW_BREWFILE=~/Brewfile
export STARSHIP_CONFIG=~/.starship.toml
export USE_YONCE=0
# export HOMEBREW_NO_INSTALL_CLEANUP=1
# export HOMEBREW_UPDATE_FREQUENCY=86400 # 24 hours

# export NVM_DIR="$HOME/.nvm"
# [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
# [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

export SSH_AUTH_SOCK=~/Library/Group\ Containers/2BUA8C4S2C.com.1password/t/agent.sock