#!/usr/bin/env zsh

# ~/.zshrc
# =============================================================================
# Executed by Z shell for interactive shells.
# See http://zsh.sourceforge.net/

clear

# -------------------------------------------------------------
# Load dependencies
# -------------------------------------------------------------
source $HOME/.exports
source $HOME/.aliases

# -------------------------------------------------------------
# Helpers
# -------------------------------------------------------------
# Kill all related processes.
killps() {
  printf "🟡 Killing processes…\n"
  kill `ps -ef | grep $1 | awk '{print $2}'`
  printf "🟡 Restart affected applications!\n"
}

# -------------------------------------------------------------
# History setup
# -------------------------------------------------------------
HISTFILE=$HOME/.zsh_history
HISTSIZE=100000
SAVEHIST=$HISTSIZ

setopt hist_ignore_all_dups # remove older duplicate entries from history
setopt hist_reduce_blanks # remove superfluous blanks from history items
setopt inc_append_history # save history entries as soon as they are entered
setopt share_history # share history between different instances of the shell
setopt auto_cd # cd by typing directory name if it's not a command
setopt correct # autocorrect
setopt correct_all # autocorrect commands
setopt auto_list # automatically list choices on ambiguous completion
setopt auto_menu # automatically use menu completion
setopt always_to_end # move cursor to end if word had one match

# -------------------------------------------------------------
# Completion system
# -------------------------------------------------------------
# autoload -Uz compinit && compinit
# autoload bashcompinit && bashcompinit # load bashcompinit for some old bash completions

# -------------------------------------------------------------
# Load private settings
# -------------------------------------------------------------
[ -f ~/.zsh.local ] && source ~/.zsh.local

# -------------------------------------------------------------
# Plugins
# -------------------------------------------------------------
# Set up fzf key bindings and fuzzy completion
# https://github.com/junegunn/fzf
# source <(fzf --zsh)

# Init zoxide
# https://github.com/ajeetdsouza/zoxide
# eval "$(zoxide init zsh)"

# -------------------------------------------------------------
# Prompt
# -------------------------------------------------------------
if [[ ! -f ~/.zsh/yonce/yonce.zsh ]]; then
  eval "$(starship init zsh)" # https://starship.rs/
else
  [[ $USE_YONCE -eq 1 ]] && source "$HOME/.zsh/yonce/yonce.zsh" # Yoncé
fi
